# OLS vs Ridge

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model,metrics
from sklearn.model_selection import GridSearchCV, train_test_split

In [2]:
df = pd.read_stata('http://fmwww.bc.edu/ec-p/data/wooldridge/card.dta')
df

id  nearc2  nearc4  educ   age  fatheduc  motheduc    weight  \
0        2.0     0.0     0.0   7.0  29.0       NaN       NaN  158413.0   
1        3.0     0.0     0.0  12.0  27.0       8.0       8.0  380166.0   
2        4.0     0.0     0.0  12.0  34.0      14.0      12.0  367470.0   
3        5.0     1.0     1.0  11.0  27.0      11.0      12.0  380166.0   
4        6.0     1.0     1.0  12.0  34.0       8.0       7.0  367470.0   
...      ...     ...     ...   ...   ...       ...       ...       ...   
3005  5218.0     0.0     1.0  12.0  25.0       8.0      12.0   82135.0   
3006  5219.0     0.0     1.0  13.0  34.0       NaN       NaN   88765.0   
3007  5220.0     0.0     1.0  12.0  24.0      11.0       NaN   89271.0   
3008  5221.0     0.0     1.0  12.0  31.0       NaN       NaN  110376.0   
3009  5225.0     0.0     1.0  13.0  26.0       NaN       NaN   81081.0   

      momdad14  sinmom14  ...  smsa66   wage  enroll   KWW     IQ  married  \
0          1.0       0.0  ...     1.0  548.0     0.0  15.0    NaN      1.0   
1          1.0       0.0  ...     1.0  481.0     0.0  35.0   93.0      1.0   
2          1.0       0.0  ...     1.0  721.0     0.0  42.0  103.0      1.0   
3          1.0       0.0  ...     1.0  250.0     0.0  25.0   88.0      1.0   
4          1.0       0.0  ...     1.0  729.0     0.0  34.0  108.0      1.0   
...        ...       ...  ...     ...    ...     ...   ...    ...      ...   
3005       1.0       0.0  ...     0.0  335.0     0.0  15.0    NaN      1.0   
3006       1.0       0.0  ...     0.0  481.0     0.0  43.0    NaN      1.0   
3007       0.0       0.0  ...     0.0  500.0     0.0  25.0  109.0      1.0   
3008       1.0       0.0  ...     0.0  713.0     0.0  32.0  107.0      1.0   
3009       0.0       0.0  ...     0.0  525.0     1.0  27.0    NaN      1.0   

      libcrd14  exper     lwage  expersq  
0          0.0   16.0  6.306275    256.0  
1          1.0    9.0  6.175867     81.0  
2          1.0   16.0  6.580639    256.0  
3          1.0   10.0  5.521461    100.0  
4          0.0   16.0  6.591674    256.0  
...        ...    ...       ...      ...  
3005       0.0    7.0  5.814130     49.0  
3006       1.0   15.0  6.175867    225.0  
3007       0.0    6.0  6.214608     36.0  
3008       1.0   13.0  6.569481    169.0  
3009       0.0    7.0  6.263398     49.0  

[3010 rows x 34 columns]

In [3]:
df = df.fillna(df.median())
df

id  nearc2  nearc4  educ   age  fatheduc  motheduc    weight  \
0        2.0     0.0     0.0   7.0  29.0      10.0      12.0  158413.0   
1        3.0     0.0     0.0  12.0  27.0       8.0       8.0  380166.0   
2        4.0     0.0     0.0  12.0  34.0      14.0      12.0  367470.0   
3        5.0     1.0     1.0  11.0  27.0      11.0      12.0  380166.0   
4        6.0     1.0     1.0  12.0  34.0       8.0       7.0  367470.0   
...      ...     ...     ...   ...   ...       ...       ...       ...   
3005  5218.0     0.0     1.0  12.0  25.0       8.0      12.0   82135.0   
3006  5219.0     0.0     1.0  13.0  34.0      10.0      12.0   88765.0   
3007  5220.0     0.0     1.0  12.0  24.0      11.0      12.0   89271.0   
3008  5221.0     0.0     1.0  12.0  31.0      10.0      12.0  110376.0   
3009  5225.0     0.0     1.0  13.0  26.0      10.0      12.0   81081.0   

      momdad14  sinmom14  ...  smsa66   wage  enroll   KWW     IQ  married  \
0          1.0       0.0  ...     1.0  548.0     0.0  15.0  103.0      1.0   
1          1.0       0.0  ...     1.0  481.0     0.0  35.0   93.0      1.0   
2          1.0       0.0  ...     1.0  721.0     0.0  42.0  103.0      1.0   
3          1.0       0.0  ...     1.0  250.0     0.0  25.0   88.0      1.0   
4          1.0       0.0  ...     1.0  729.0     0.0  34.0  108.0      1.0   
...        ...       ...  ...     ...    ...     ...   ...    ...      ...   
3005       1.0       0.0  ...     0.0  335.0     0.0  15.0  103.0      1.0   
3006       1.0       0.0  ...     0.0  481.0     0.0  43.0  103.0      1.0   
3007       0.0       0.0  ...     0.0  500.0     0.0  25.0  109.0      1.0   
3008       1.0       0.0  ...     0.0  713.0     0.0  32.0  107.0      1.0   
3009       0.0       0.0  ...     0.0  525.0     1.0  27.0  103.0      1.0   

      libcrd14  exper     lwage  expersq  
0          0.0   16.0  6.306275    256.0  
1          1.0    9.0  6.175867     81.0  
2          1.0   16.0  6.580639    256.0  
3          1.0   10.0  5.521461    100.0  
4          0.0   16.0  6.591674    256.0  
...        ...    ...       ...      ...  
3005       0.0    7.0  5.814130     49.0  
3006       1.0   15.0  6.175867    225.0  
3007       0.0    6.0  6.214608     36.0  
3008       1.0   13.0  6.569481    169.0  
3009       0.0    7.0  6.263398     49.0  

[3010 rows x 34 columns]

In [4]:
X = ['married', 'exper', 'expersq',
     'nearc2', 'nearc4', 'fatheduc', 'motheduc',
     'weight', 'momdad14', 'sinmom14', 'step14', 
     'reg661', 'reg662', 'reg663', 'reg664', 
     'reg665', 'reg666', 'reg667', 'reg668',
     'south66', 'black', 'smsa', 'south', 'smsa66']
Y = ['educ']

In [5]:
results = {}
r2_train = []
r2_test = []
X_train, X_test, y_train, y_test = train_test_split(df[X], df[Y], test_size= 0.2)

In [6]:
OLS=linear_model.LinearRegression()
model_OLS=OLS.fit(X_train, y_train)

In [7]:
y_pred_OLS_train=model_OLS.predict(X_train)
r2_OLS_train=metrics.r2_score(y_train,y_pred_OLS_train)
r2_train.append(r2_OLS_train)

In [8]:
y_pred_OLS_test=model_OLS.predict(X_test)
r2_OLS_test=metrics.r2_score(y_test,y_pred_OLS_test)
r2_test.append(r2_OLS_test)

In [9]:
results['OLS'] = [np.mean(r2_train), np.mean(r2_test)]

In [10]:
RIDGE=linear_model.Ridge()
model_RIDGE=RIDGE.fit(X_train, y_train)

/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.43713e-14): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,


In [11]:
y_pred_RIDGE_train=model_RIDGE.predict(X_train)
r2_RIDGE_train=metrics.r2_score(y_train,y_pred_RIDGE_train)
r2_train.append(r2_RIDGE_train)

In [12]:
y_pred_RIDGE_test=model_RIDGE.predict(X_test)
r2_RIDGE_test=metrics.r2_score(y_test,y_pred_RIDGE_test)
r2_test.append(r2_RIDGE_test)

In [13]:
results['RIDGE'] = [np.mean(r2_train), np.mean(r2_test)]
results

{'OLS': [0.5465100302961412, 0.4751789769514042],
 'RIDGE': [0.5465091849177278, 0.4753951216854771]}

In [14]:
df_results=pd.DataFrame(data=results, index=['Train','Test'])
df_results

OLS     RIDGE
Train  0.546510  0.546509
Test   0.475179  0.475395

In [15]:
r2_train2 = []
r2_test2 = []

In [16]:
ridge_params = {'alpha':[550, 580, 600, 620, 650]}
RIDGE2=GridSearchCV(RIDGE, param_grid=ridge_params,cv=10)

In [17]:
RIDGE2.fit(df[X], df[Y]).best_estimator_
y_pred_RIDGE2_train=model_RIDGE.predict(X_train)
r2_RIDGE2_train=metrics.r2_score(y_train,y_pred_RIDGE2_train)
r2_train2.append(r2_RIDGE2_train)

/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=5.99208e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=5.92483e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=5.81707e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=6.11327e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=6.399

/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=8.06804e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=7.97601e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/home/marianne/.local/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=5.60146e-12): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,


# RIDGE2.fit(df[X], df[Y]).best_estimator_
y_pred_RIDGE2_test=model_RIDGE.predict(X_test)
r2_RIDGE2_test=metrics.r2_score(y_test,y_pred_RIDGE2_test)
r2_test2.append(r2_RIDGE2_test)

In [18]:
results['RIDGE2'] = [np.mean(r2_train2), np.mean(r2_test2)]

/home/marianne/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/marianne/.local/lib/python3.8/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [19]:
df_results=pd.DataFrame(data=results, index=['Train','Test'])
df_results

OLS     RIDGE    RIDGE2
Train  0.546510  0.546509  0.546508
Test   0.475179  0.475395       NaN

# Logistic regression on the iris dataset

In [20]:
from sklearn import datasets
iris = datasets.load_iris()
dataX = iris.data
datay = iris.target

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataX, datay, test_size=0.33, random_state=42)

# Fit the model

In [22]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)  

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

# Evaluation

In [23]:
pipe.score(X_train, y_train)

0.96

In [24]:
pipe.score(X_test, y_test)

0.98

# Cross validation

In [25]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(pipe, dataX, datay, cv=5)
scores

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

# SVM

In [26]:
from sklearn.svm import SVC

To simplify we remove the label 0

In [27]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X = X[y != 0, :2]
y = y[y != 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [28]:
pipe_svm_lin = make_pipeline(StandardScaler(),SVC(kernel='linear',gamma='auto'))
pipe_svm_lin.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto', kernel='linear'))])

In [29]:
pipe_svm_lin.score(X_test, y_test)

0.6666666666666666

In [30]:
cross_val_score(pipe_svm_lin, X, y, cv=7)

array([0.53333333, 0.73333333, 0.78571429, 0.5       , 0.71428571,
       0.71428571, 0.85714286])

# Decision Trees 

# Quantile regression

In [31]:
import numpy as np
import matplotlib.pyplot as plt 

import pandas as pd  
import seaborn as sns 
from sklearn import metrics
from sklearn.datasets import load_boston
boston_dataset = load_boston()
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [32]:
X = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
y = pd.Series(boston_dataset.target)
X_train, X_test, y_train, y_test = train_test_split(X, y)

# Random Forest

In [33]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(n_estimators=200)
clf.fit(X_train, y_train)
Z = clf.predict(X_test)
accuracy=clf.score(X_test,y_test)
accuracy

0.8308698535356415

In [34]:
cross_val_score(clf, X, y, cv=7)

array([0.74749803, 0.82737621, 0.78843733, 0.75189105, 0.66737884,
       0.31141503, 0.49068497])

# GBT

In [35]:
from sklearn.ensemble import GradientBoostingRegressor
regressor = GradientBoostingRegressor(
    max_depth=2,
    n_estimators=3,
    learning_rate=1.0
)
regressor.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=1.0, max_depth=2, n_estimators=3)

In [36]:
cross_val_score(regressor, X, y, cv=7)

array([0.50903989, 0.53277028, 0.64560748, 0.43795639, 0.14842912,
       0.17755251, 0.23463445])